/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.81
 * Generated at: 2022-07-22 09:13:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.class_;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ClassDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/D:/third_project/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/COBS/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/class/../include/header.jsp", Long.valueOf(1658474821385L));
    _jspx_dependants.put("/class/../include/footer.jsp", Long.valueOf(1597885966000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1597885966000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write("\n");
      out.write("    \n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"utf-8\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("  <meta name=\"description\" content=\"\">\n");
      out.write("  <meta name=\"author\" content=\"\">\n");
      out.write("  <title>모두를 위한 코딩 학습 공간 COBS</title>\n");
      out.write("  <!-- Bootstrap core CSS -->\n");
      out.write("  <link href=\"/Tutoring/vendor/bootstrap/css/bootstrap.css\"  rel=\"stylesheet\">\n");
      out.write("  <!-- Custom fonts for this template -->\n");
      out.write("  <link href=\"/Tutoring/vendor/fontawesome-free/css/all.css\" rel=\"stylesheet\">\n");
      out.write("  <link href=\"/Tutoring/vendor/simple-line-icons/css/simple-line-icons.css\"  rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic\"  rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("  <!-- Custom styles for this template -->\n");
      out.write("  <link href=\"/Tutoring/css/landing-page.css\" rel=\"stylesheet\">\n");
      out.write("  \n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\n");
      out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js\"></script>\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\n");
      out.write("  \n");
      out.write("\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("  <!-- Navigation -->\n");
      out.write("  <nav class=\"navbar navbar-white bg-white static-top\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("         <a class=\"navbar-brand\" href=\"/Tutoring/index.jsp\"><img src=\"/Tutoring/img/logo1.png\" alt=\"CBS\"></a>\n");
      out.write("         <a class=\"navbar-nav\" href=\"/Tutoring/include/about.jsp\">COBS?</a>\n");
      out.write("         <a class=\"navbar-nav\" href=\"/Tutoring/class/courseList\">과정</a>\n");
      out.write("         <a class=\"navbar-nav\" href=\"/Tutoring/qna/NewFile.jsp\">QnA</a>\n");
      out.write("    </div>\n");
      out.write("      ");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("  \n");
      out.write("  	\n");
      out.write("  </nav>\n");
      out.write("  \n");
      out.write("<!-- Bootstrap core JavaScript -->\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\n");
      out.write("<script src=\"/Tutoring/vendor/jquery/jquery.js\"></script>\n");
      out.write("<script src=\"/Tutoring/vendor/bootstrap/js/bootstrap.bundle.js\"></script>");
      out.write("\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\n");
      out.write("<style>\n");
      out.write("a{\n");
      out.write("	text-decoration: none;\n");
      out.write("}\n");
      out.write("a:hover{\n");
      out.write("	text-decoration: none;\n");
      out.write("}\n");
      out.write(".back2{\n");
      out.write("	margin-top: 20px;\n");
      out.write("	background-color: #f8f9fa;\n");
      out.write("	border-radius: 20px;\n");
      out.write("}\n");
      out.write("#frm{\n");
      out.write("	margin: 0 auto;\n");
      out.write("	width: 50%;\n");
      out.write("}\n");
      out.write(".button{\n");
      out.write("	text-align: center;\n");
      out.write("	margin: 0 auto;\n");
      out.write("	padding: 20px;\n");
      out.write("}\n");
      out.write(".sidebar{\n");
      out.write("	float: left;\n");
      out.write("	width: 200px;\n");
      out.write("	height:200px;\n");
      out.write("	margin-top: 60px;\n");
      out.write("	margin-left: 60px;\n");
      out.write("}\n");
      out.write(".sidebar ul{\n");
      out.write("	list-style: none;\n");
      out.write("}\n");
      out.write(".sidebar ul a{\n");
      out.write("	line-height: 2em;\n");
      out.write("}\n");
      out.write(".thumb-image{\n");
      out.write("	float:left;\n");
      out.write("	width:200px;\n");
      out.write("	position:relative;\n");
      out.write("	padding:5px;\n");
      out.write("}\n");
      out.write("img{\n");
      out.write("	width:200px;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("<aside class=\"sidebar\">\n");
      out.write("	<ul id=\"menu\">\n");
      out.write("        <li><h5><a href=\"/Tutoring/class/ClassInsert.jsp\"> 강의입력</a></h5></li>\n");
      out.write("        <li><h5><a href=\"/Tutoring/class/ClassList.jsp\"> 강의목록</a></h5></li>\n");
      out.write("        <li><h5><a href=\"/Tutoring/member/Adminview\"> 계정설정</a></h5></li>\n");
      out.write("	</ul>\n");
      out.write("</aside>\n");
      out.write("<div class=\"container\">\n");
      out.write("<br/>\n");
      out.write("<h5>강의입력</h5>\n");
      out.write("<div class=\"back2\">\n");
      out.write("<form action=\"ClassUpdate\" method=\"post\" id=\"frm\" enctype=\"multipart/form-data\">\n");
      out.write("  <br/><br/>\n");
      out.write("  	<div id=\"image-holder\"></div>\n");
      out.write("      <img src=\"/Tutoring/upload/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.uploadFile}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("  <div class=\"input-group mb-3\">\n");
      out.write("    <div class=\"input-group-prepend\">\n");
      out.write("      <span class=\"input-group-text\">강의 이미지</span>\n");
      out.write("    </div>\n");
      out.write("      <input type=\"file\" class=\"form-control\" id=\"uploadFile\" name=\"uploadFile\">\n");
      out.write("      <input type=\"text\" class=\"form-control\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.uploadFile}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("  </div>\n");
      out.write("  <br/>\n");
      out.write("  \n");
      out.write("  <div class=\"input-group mb-3\">\n");
      out.write("    <div class=\"input-group-prepend\">\n");
      out.write("      <span class=\"input-group-text\">강의분류</span>\n");
      out.write("    </div>\n");
      out.write("      <select name=\"clevel\" id=\"clevel\" name=\"clevel\">\n");
      out.write("      	<option value=\"basic\" class=\"form-control\" >유창한 영어의 기본 요소</option>\n");
      out.write("      	<option value=\"career\" class=\"form-control\">경력 개발</option>\n");
      out.write("      	<option value=\"expression\" class=\"form-control\">자신을 표현해보세요</option>\n");
      out.write("      	<option value=\"test\" class=\"form-control\">시험 준비</option>\n");
      out.write("      </select>\n");
      out.write("  </div>\n");
      out.write("  <br/>\n");
      out.write("  <div class=\"input-group mb-3\">\n");
      out.write("    <div class=\"input-group-prepend\">\n");
      out.write("      <span class=\"input-group-text\">강의명</span>\n");
      out.write("    </div>\n");
      out.write("      <input type=\"text\" class=\"form-control\" id=\"classname\" name=\"classname\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.classname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("  </div>\n");
      out.write("  <br/>\n");
      out.write("   \n");
      out.write("  <div class=\"input-group mb-3\">\n");
      out.write("    <div class=\"input-group-prepend\">\n");
      out.write("      <span class=\"input-group-text\">강의 주제</span>\n");
      out.write("    </div>\n");
      out.write("      <input type=\"text\" class=\"form-control\" id=\"topic\" name=\"topic\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.topic}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("  </div>\n");
      out.write("  <br/>\n");
      out.write("  \n");
      out.write("  <div class=\"input-group mb-3\">\n");
      out.write("    <div class=\"input-group-prepend\">\n");
      out.write("      <span class=\"input-group-text\">강의설명</span>\n");
      out.write("    </div>\n");
      out.write("      <textarea rows=\"5\" cols=\"20\" class=\"form-control\" id=\"content\" name=\"content\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea>\n");
      out.write("  </div>\n");
      out.write("  <br/>\n");
      out.write("  \n");
      out.write("  <div class=\"button\">\n");
      out.write(" 	  <button  id=\"send\"  class=\"btn btn-info\">저장</button>\n");
      out.write(" 	  <input type=\"button\" class=\"btn btn-danger\" value=\"강의삭제\" onclick=\"delClassCheck('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.classnum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("')\">\n");
      out.write("  </div>\n");
      out.write("<input type=\"hidden\" id=\"classnum\" name=\"classnum\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.classnum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("</form>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("<br/><br/>\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("footer{\n");
      out.write("	clear: both;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write(" <!-- Footer -->\n");
      out.write("  <footer class=\"footer bg-light\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("      <div class=\"row\">\n");
      out.write("        <div class=\"col-lg-6 h-100 text-center text-lg-left my-auto\">\n");
      out.write("          <ul class=\"list-inline mb-2\">\n");
      out.write("            <li class=\"list-inline-item\">\n");
      out.write("              <a href=\"#\">About</a>\n");
      out.write("            </li>\n");
      out.write("            <li class=\"list-inline-item\">&sdot;</li>\n");
      out.write("            <li class=\"list-inline-item\">\n");
      out.write("              <a href=\"#\">Contact</a>\n");
      out.write("            </li>\n");
      out.write("            <li class=\"list-inline-item\">&sdot;</li>\n");
      out.write("            <li class=\"list-inline-item\">\n");
      out.write("              <a href=\"#\">Terms of Use</a>\n");
      out.write("            </li>\n");
      out.write("            <li class=\"list-inline-item\">&sdot;</li>\n");
      out.write("            <li class=\"list-inline-item\">\n");
      out.write("              <a href=\"#\">Privacy Policy</a>\n");
      out.write("            </li>\n");
      out.write("          </ul>\n");
      out.write("          <p class=\"text-muted small mb-4 mb-lg-0\">&copy; Your Website 2020. All Rights Reserved.</p>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-lg-6 h-100 text-center text-lg-right my-auto\">\n");
      out.write("          <ul class=\"list-inline mb-0\">\n");
      out.write("            <li class=\"list-inline-item mr-3\">\n");
      out.write("              <a href=\"#\">\n");
      out.write("                <i class=\"fab fa-facebook fa-2x fa-fw\"></i>\n");
      out.write("              </a>\n");
      out.write("            </li>\n");
      out.write("            <li class=\"list-inline-item mr-3\">\n");
      out.write("              <a href=\"#\">\n");
      out.write("                <i class=\"fab fa-twitter-square fa-2x fa-fw\"></i>\n");
      out.write("              </a>\n");
      out.write("            </li>\n");
      out.write("            <li class=\"list-inline-item\">\n");
      out.write("              <a href=\"#\">\n");
      out.write("                <i class=\"fab fa-instagram fa-2x fa-fw\"></i>\n");
      out.write("              </a>\n");
      out.write("            </li>\n");
      out.write("          </ul>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </footer>\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("<script>\n");
      out.write("$(\"select[name=clevel] option\").each(function(){\n");
      out.write("	if($(this).val()=='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.clevel}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'){\n");
      out.write("		 $(this).prop(\"selected\", true);\n");
      out.write("	}\n");
      out.write("});\n");
      out.write("function delClassCheck(classnum){\n");
      out.write("	 if(confirm(\"삭제하시겠습니까? 삭제된 강의정보는 되돌릴 수 없습니다.\")){\n");
      out.write("    	location.href=\"delete?classnum=\"+classnum;\n");
      out.write("    }\n");
      out.write("}\n");
      out.write("$(document).ready(function(){\n");
      out.write("	$(\"#send\").click(function(){\n");
      out.write("		if($(\"#classname\").val()==\"\"){\n");
      out.write("			alert(\"강의명을 입력하세요\");\n");
      out.write("			$(\"#classname\").focus();\n");
      out.write("			return false;\n");
      out.write("		}\n");
      out.write("		if($(\"#topic\").val()==\"\"){\n");
      out.write("			alert(\"강의주제를 입력하세요\");\n");
      out.write("			$(\"#topic\").focus();\n");
      out.write("			return false;\n");
      out.write("		}\n");
      out.write("		if($(\"#content\").val()==\"\"){\n");
      out.write("			alert(\"강의설명을 입력하세요\");\n");
      out.write("			$(\"#content\").focus();\n");
      out.write("			return false;\n");
      out.write("		}\n");
      out.write("		$(\"#frm\").submit();\n");
      out.write("	})//send\n");
      out.write("	\n");
      out.write("	$(\"#uploadFile\").on('change', function () {\n");
      out.write("        if (typeof (FileReader) != \"undefined\") {\n");
      out.write("            var image_holder = $(\"#image-holder\");\n");
      out.write("            image_holder.empty();\n");
      out.write("            var reader = new FileReader();\n");
      out.write("            reader.onload = function (e) {\n");
      out.write("                $(\"<img />\", {\n");
      out.write("                    \"src\": e.target.result,\n");
      out.write("                    \"class\": \"thumb-image\"\n");
      out.write("                }).appendTo(image_holder);\n");
      out.write("            }\n");
      out.write("            image_holder.show();\n");
      out.write("            reader.readAsDataURL($(this)[0].files[0]);\n");
      out.write("        } else {\n");
      out.write("            alert(\"이 브라우저에서 지원하지 않는 확장자 입니다.\");\n");
      out.write("        }\n");
      out.write("    });\n");
      out.write("});//document\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("     	");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("    	");
          if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("    	");
          if (_jspx_meth_c_005fwhen_005f2(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("     ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /class/../include/header.jsp(39,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty sessionScope.userid}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("		    <ul class=\"navbar-nav\">\n");
          out.write("		      <li class=\"nav-item\">\n");
          out.write("		      	<a class=\"btn btn-gray\" href=\"/Tutoring/member/login\">로그인</a>\n");
          out.write("			    <a class=\"btn btn-primary\" href=\"/Tutoring/member/insert\">회원가입</a>\n");
          out.write("		      </li>\n");
          out.write("		  	</ul>\n");
          out.write("    	");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f1_reused = false;
    try {
      _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /class/../include/header.jsp(47,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.admin==1}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
      if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("		    <ul class=\"navbar-nav\">\n");
          out.write("		      <li class=\"nav-item\">\n");
          out.write("		      	<a class=\"btn btn-gray\" href=\"/Tutoring/member/Adminview\">관리자</a>\n");
          out.write("			    <a class=\"btn btn-primary\" href=\"/Tutoring/member/logout\">로그아웃</a>\n");
          out.write("		      </li>\n");
          out.write("		  	</ul>\n");
          out.write("    	");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      _jspx_th_c_005fwhen_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f2 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f2_reused = false;
    try {
      _jspx_th_c_005fwhen_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /class/../include/header.jsp(55,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.admin==0}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f2 = _jspx_th_c_005fwhen_005f2.doStartTag();
      if (_jspx_eval_c_005fwhen_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("    		<ul class=\"navbar-nav\">\n");
          out.write("		      <li class=\"nav-item\">\n");
          out.write("		      	<a class=\"btn btn-gray\" href=\"/Tutoring/member/view\">내계정</a>\n");
          out.write("			    <a class=\"btn btn-info\" href=\"/Tutoring/member/logout\">로그아웃</a>\n");
          out.write("		      </li>\n");
          out.write("		  	</ul>\n");
          out.write("    	");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f2);
      _jspx_th_c_005fwhen_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f2_reused);
    }
    return false;
  }
}
